theme: jekyll-theme-hacker
title: root💀d4rk5id3:~#
favicon: https://twitter.com/NwadinobiJude/photo
description: Hack. Eat. Sleep. Repeat!!!
show_downloads: false
show_repo: false

gems:
- jekyll-sitemap

whitelist:
- jekyll-sitemap
